baseurl: "http://kijtra.com/"
languageCode: "ja-JP"
title: "きじとら"
theme: "kijtra"

contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"

canonifyurls: true
uglyURLs: true
metaDataformat: "yaml"

pygmentsstyle: "monokai"
pygmentsuseclasses: false

taxonomies:
  category: "categories"
  tag: "tags"

params:
  description: "Webのこととかそのたもろもろ"
  author: "きじとら"
